export const users = [
    {
      id: 1,
      name: "Michael Holz",
      dateCreated: "04/10/2013",
      role: "Admin",
      status: "Active",
      avatar: "https://i.pravatar.cc/40?img=1",
    },
    {
      id: 2,
      name: "Paula Wilson",
      dateCreated: "05/08/2014",
      role: "Publisher",
      status: "Active",
      avatar: "https://i.pravatar.cc/40?img=2",
    },
    {
      id: 3,
      name: "Antonio Moreno",
      dateCreated: "11/05/2015",
      role: "Publisher",
      status: "Suspended",
      avatar: "https://i.pravatar.cc/40?img=3",
    },
    {
      id: 4,
      name: "Mary Saveley",
      dateCreated: "06/09/2016",
      role: "Reviewer",
      status: "Active",
      avatar: "https://i.pravatar.cc/40?img=4",
    },
    {
      id: 5,
      name: "Robert Downey",
      dateCreated: "02/12/2017",
      role: "Editor",
      status: "Inactive",
      avatar: "https://i.pravatar.cc/40?img=5",
    },
    {
      id: 6,
      name: "Emily Clark",
      dateCreated: "08/15/2018",
      role: "Moderator",
      status: "Active",
      avatar: "https://i.pravatar.cc/40?img=6",
    },
    {
      id: 7,
      name: "John Doe",
      dateCreated: "01/20/2019",
      role: "Admin",
      status: "Suspended",
      avatar: "https://i.pravatar.cc/40?img=7",
    },
    {
      id: 8,
      name: "Sophia Patel",
      dateCreated: "07/25/2020",
      role: "Reviewer",
      status: "Active",
      avatar: "https://i.pravatar.cc/40?img=8",
    },
    {
      id: 9,
      name: "Liam Johnson",
      dateCreated: "03/30/2021",
      role: "Publisher",
      status: "Inactive",
      avatar: "https://i.pravatar.cc/40?img=9",
    },
    {
      id: 10,
      name: "Olivia White",
      dateCreated: "10/10/2022",
      role: "Editor",
      status: "Active",
      avatar: "https://i.pravatar.cc/40?img=10",
    },
  ];
  